language: node_js
node_js:
 - "node"
env:
  global:
    - MONGO_URI=mongodb://127.0.0.1/her_story_told
    - SECRET=thisismyappsecret
    - DEBUG=true
    - TEST=true
services: mongodb
before_script:
- tsc
